### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by uhlhosting** [marketgoo/cpanel.plugin#1]
curl -Lks http://git.io/marketgoo.cpanel.uninstall | sh was runned from cmd line on server

Yet I do have it in Cpanel for all users:

http://prntscr.com/7lizkp

What to do to fully remove it? I run WHM/Cpanel on Centos 6.6

**Comment by twoixter** [comment]
Hi @highacid , there might be a bug with the uninstall script and the _dynamicui_ feature of latest cPanel theme versions. We'll be thoroughly checking this and issue a new version of the uninstaller.

In the mean time if you want to uninstall it right away, try the following steps:
- In the cmd line on the server logged in as root, change to the `/usr/local/cpanel/base/frontend` directory.
- Issue the following command: `find . -name dynamicui_marketgoo*`
- Remove all the files listed by the above command. There'll be 4 files total, 2 for each of the `x3` and `paper_lantern` themes. (There will be more than 4 if you have additional themes installed).
- After removal, refresh the cPanel UI (perhaps you'll need to log out and log in again).

**Comment by twoixter** [comment]
Hi again @highacid , we've fixed the bug and it is correctly uninstalling now. You can run the uninstalling procedure again!

PS: If the uninstaller says that `MarketGoo plug-in for cPanel/WHM already unistalled!` you might need to install again and then uninstall.

FYI: Fixed in the commit 21dd1491239048b32c082ac31c7be34dff37e18a
